# Generated by Django 4.1.13 on 2026-04-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
